### ISSUE TITLE
KH1 crashes constantly after update

### ISSUE THREAD

**Issue by NezomiFloof** [Sirius902/LuaBackend#20]
I was one of the people who moved from Epic to Steam, and I can confirm now that no scripts work here. I don't know if this is a problem with [PC Speedrun Tools](https://github.com/Denhonator/KHPCSpeedrunTools) or what, but no matter what script I load into KH1, it always crashes. Timing is entirely random too.

**Comment by anogowski** [comment]
@NezomiFloof 

While I have not tried [PC Speedrun Tools](https://github.com/Denhonator/KHPCSpeedrunTools).
I did get the following mods to not crash in KH1:
![image](https://github.com/Sirius902/LuaBackend/assets/6656694/bbda23ae-d7b8-47a3-aa3f-524e54fa1020)


Your LuaBackend.toml for **Steam** should look like this:
```toml
[kh1]
scripts = [{ path = "scripts/kh1/", relative = true }]
exe = "KINGDOM HEARTS FINAL MIX.exe"
game_docs = "My Games/KINGDOM HEARTS HD 1.5+2.5 ReMIX"

[kh2]
scripts = [{ path = "scripts/kh2/", relative = true }]
exe = "KINGDOM HEARTS II FINAL MIX.exe"
game_docs = "My Games/KINGDOM HEARTS HD 1.5+2.5 ReMIX"

[bbs]
scripts = [{ path = "scripts/bbs/", relative = true }]
exe = "KINGDOM HEARTS Birth by Sleep FINAL MIX.exe"
game_docs = "My Games/KINGDOM HEARTS HD 1.5+2.5 ReMIX"

[recom]
scripts = [{ path = "scripts/recom/", relative = true }]
exe = "KINGDOM HEARTS Re_Chain of Memories.exe"
game_docs = "My Games/KINGDOM HEARTS HD 1.5+2.5 ReMIX"

[kh3d]
scripts = [{ path = "scripts/kh3d/", relative = true }]
exe = "KINGDOM HEARTS Dream Drop Distance.exe"
game_docs = "My Games/KINGDOM HEARTS HD 2.8 Final Chapter Prologue"
```

In all of the lua scripts find any type of offset and delete it
ex:
- " - offset"
- "-offset"
- " - SteamOffset"
